"""
Report Generation Engine
==========================

Generates professional bug bounty reports in multiple formats:
- Markdown (HackerOne / Bugcrowd style)
- HTML
- JSON
- PDF

Each report includes all required fields for bounty submission.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, BaseLoader

from bbhunter.config import get_config
from bbhunter.logger import get_logger
from bbhunter.models import (
    ExploitChain,
    Report,
    Severity,
    Vulnerability,
    VulnCategory,
)

logger = get_logger()


# -----------------------------------------------------------------------
# Markdown Templates
# -----------------------------------------------------------------------

HACKERONE_TEMPLATE = """# {{ title }}

## Summary
{{ description }}

## Severity
**{{ severity | upper }}**
{% if cvss_score > 0 %}
CVSS Score: {{ cvss_score }}
{% endif %}

## Vulnerability Type
{{ category }}

## URL / Endpoint
`{{ url }}`

{% if parameter %}
## Affected Parameter
`{{ parameter }}`
{% endif %}

## Steps to Reproduce
{% for step in steps_to_reproduce %}
{{ loop.index }}. {{ step }}
{% endfor %}

## Proof of Concept
{% if payload %}
### Payload
```
{{ payload }}
```
{% endif %}

{% if evidence %}
### Evidence
```
{{ evidence }}
```
{% endif %}

{% if request %}
### HTTP Request
```http
{{ request }}
```
{% endif %}

{% if response %}
### HTTP Response (truncated)
```http
{{ response }}
```
{% endif %}

## Impact
{{ impact }}

## Remediation
{{ remediation }}

---
*Report generated by BugBounty Hunter Suite on {{ generated_at }}*
"""

BUGCROWD_TEMPLATE = """# Bug Report: {{ title }}

**Severity:** {{ severity | upper }}
**Category:** {{ category }}

---

## Description
{{ description }}

## Target
- **URL:** `{{ url }}`
{% if parameter %}- **Parameter:** `{{ parameter }}`{% endif %}

## Reproduction Steps
{% for step in steps_to_reproduce %}
{{ loop.index }}. {{ step }}
{% endfor %}

## Proof of Concept

{% if payload %}
**Payload Used:**
```
{{ payload }}
```
{% endif %}

{% if evidence %}
**Server Response Evidence:**
```
{{ evidence }}
```
{% endif %}

## Business Impact
{{ impact }}

## Suggested Fix
{{ remediation }}

---
*Generated: {{ generated_at }} | BugBounty Hunter Suite*
"""

EXECUTIVE_SUMMARY_TEMPLATE = """# Security Assessment Executive Summary

**Target:** {{ target_domain }}
**Date:** {{ generated_at }}
**Scanner:** BugBounty Hunter Suite v1.0

---

## Overview

| Metric | Value |
|--------|-------|
| Total Findings | {{ stats.total_findings }} |
| Critical | {{ stats.critical }} |
| High | {{ stats.high }} |
| Medium | {{ stats.medium }} |
| Low | {{ stats.low }} |
| Exploit Chains | {{ stats.chains }} |

## Risk Summary

{% for risk, present in impact.items() %}
- **{{ risk | replace('_', ' ') | title }}:** {{ '⚠️ YES' if present else '✅ No' }}
{% endfor %}

## Critical & High Findings

{% for vuln in critical_vulns %}
### {{ loop.index }}. {{ vuln.title }}
- **Severity:** {{ vuln.severity | upper }}
- **Category:** {{ vuln.category }}
- **URL:** `{{ vuln.url }}`
- **Confidence:** {{ "%.0f" | format(vuln.confidence * 100) }}%

{% endfor %}

## Exploit Chains

{% for chain in chains %}
### {{ chain.title }}
- **Combined Severity:** {{ chain.combined_severity | upper }}
- **Impact:** {{ chain.impact }}
- **Attack Path:**
{% for step in chain.attack_path %}
  {{ loop.index }}. {{ step }}
{% endfor %}

{% endfor %}

## Recommendations

1. Address all Critical and High severity findings immediately
2. Implement security headers across all endpoints
3. Review authentication and authorization mechanisms
4. Deploy WAF rules for detected attack patterns
5. Conduct regular security assessments

---
*This report was generated by BugBounty Hunter Suite. All testing was performed with explicit authorization.*
"""


class ReportEngine:
    """
    Professional bug bounty report generator.
    
    Generates reports in HackerOne / Bugcrowd format
    with all required fields for bounty submission.
    """

    def __init__(self):
        self.config = get_config()
        self.env = Environment(loader=BaseLoader(), autoescape=False)
        self.reports_dir = Path(self.config.app.reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def generate_vulnerability_report(
        self,
        vulnerability: Vulnerability,
        template: str = "hackerone",
    ) -> Report:
        """
        Generate a single vulnerability report.
        
        Args:
            vulnerability: The vulnerability to report.
            template: 'hackerone' or 'bugcrowd'.
        """
        template_str = HACKERONE_TEMPLATE if template == "hackerone" else BUGCROWD_TEMPLATE
        tmpl = self.env.from_string(template_str)

        content = tmpl.render(
            title=vulnerability.title,
            description=vulnerability.description,
            severity=vulnerability.severity.value,
            category=vulnerability.category.value,
            url=vulnerability.url,
            parameter=vulnerability.parameter,
            payload=vulnerability.payload,
            evidence=vulnerability.evidence,
            request=vulnerability.request,
            response=vulnerability.response[:1000] if vulnerability.response else "",
            steps_to_reproduce=vulnerability.steps_to_reproduce,
            impact=vulnerability.impact,
            remediation=vulnerability.remediation,
            cvss_score=vulnerability.cvss_score,
            generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        )

        report = Report(
            target_id=vulnerability.target_id,
            title=vulnerability.title,
            vulnerability=vulnerability,
            format="markdown",
            content=content,
        )

        # Save to file
        filename = self._sanitize_filename(vulnerability.title)
        filepath = self.reports_dir / f"{filename}.md"
        filepath.write_text(content)
        logger.info(f"📄 Report saved: {filepath}")

        return report

    def generate_executive_summary(
        self,
        target_domain: str,
        vulnerabilities: list[Vulnerability],
        chains: list[ExploitChain],
        analysis_results: dict[str, Any],
    ) -> str:
        """Generate an executive summary report."""
        tmpl = self.env.from_string(EXECUTIVE_SUMMARY_TEMPLATE)

        critical_vulns = [
            v for v in vulnerabilities
            if v.severity in (Severity.CRITICAL, Severity.HIGH)
        ]

        content = tmpl.render(
            target_domain=target_domain,
            generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            stats=analysis_results.get("statistics", {}),
            impact=analysis_results.get("impact_summary", {}),
            critical_vulns=critical_vulns,
            chains=chains,
        )

        filepath = self.reports_dir / f"executive_summary_{target_domain}.md"
        filepath.write_text(content)
        logger.info(f"📊 Executive summary saved: {filepath}")

        return content

    def generate_json_report(
        self,
        target_domain: str,
        vulnerabilities: list[Vulnerability],
        chains: list[ExploitChain],
        analysis_results: dict[str, Any],
    ) -> str:
        """Generate a JSON report for programmatic consumption."""
        report_data = {
            "metadata": {
                "tool": "BugBounty Hunter Suite",
                "version": "1.0.0",
                "target": target_domain,
                "generated_at": datetime.utcnow().isoformat(),
            },
            "statistics": analysis_results.get("statistics", {}),
            "impact_summary": analysis_results.get("impact_summary", {}),
            "vulnerabilities": [v.model_dump() for v in vulnerabilities],
            "exploit_chains": [c.model_dump() for c in chains],
            "attack_graph": analysis_results.get("attack_graph", {}),
        }

        content = json.dumps(report_data, indent=2, default=str)
        filepath = self.reports_dir / f"report_{target_domain}.json"
        filepath.write_text(content)
        logger.info(f"📋 JSON report saved: {filepath}")

        return content

    def generate_all_reports(
        self,
        target_domain: str,
        vulnerabilities: list[Vulnerability],
        chains: list[ExploitChain],
        analysis_results: dict[str, Any],
    ) -> list[str]:
        """Generate all report formats."""
        generated = []

        # Individual vulnerability reports
        for vuln in vulnerabilities:
            if vuln.severity in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM):
                report = self.generate_vulnerability_report(vuln)
                generated.append(report.content)

        # Executive summary
        summary = self.generate_executive_summary(
            target_domain, vulnerabilities, chains, analysis_results
        )
        generated.append(summary)

        # JSON report
        json_report = self.generate_json_report(
            target_domain, vulnerabilities, chains, analysis_results
        )
        generated.append(json_report)

        return generated

    def _sanitize_filename(self, name: str) -> str:
        """Sanitize a string for use as a filename."""
        safe = "".join(c if c.isalnum() or c in ("-", "_", " ") else "_" for c in name)
        return safe[:100].strip().replace(" ", "_")
