version: "3.9"

services:
  api:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=******postgres:5432/bbp
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  lab:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.lab
    ports:
      - "8888:8888"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bbp
      POSTGRES_PASSWORD: bbp
      POSTGRES_DB: bbp
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bbp"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pg-data:
